<?php
$strScene = 'Escena';
$strSatelite = 'Sat&eacute;lite';
$strSensor = 'Sensor';
$strBase = '&Oacute;rbita';
$strPonto = 'Punto';
$strData = 'Fecha del Pasaje';
$strTLLat = 'Latitud Norte';
$strTLLon = 'Longitud Oeste';
$strBRLat = 'Latitud Sur';
$strBRLon = 'Longitud Este';
$strCenter = 'Tiempo Central';
$strStartT = 'Tiempo Inicial';
$strStopT = 'Tiempo Final';
$strIngest = 'Fecha de Ingest&atilde;o'; 
$strImg = 'Orientaci&oacute;n de la Imagen';
$strPerMissSwaths = 'Barridos Perdidos (%)';
$strMetodoCobert = 'M&eacute;todo de Cobertura de Nubes';
$strOrbita = 'Revoluci&oacute;n';
$strBitSlips = 'P&eacute;rdida de Bits';
$strMissSwaths = 'Barridos Perdidos';
$strSyncLosses = 'P&eacute;rdida de Sincronismo';
$strCobertura = 'Cobertura de Nubes';
$strOffNadirAngle = '&Aacute;ngulo Nadir';
$strSunIncidenceAngle = '&Aacute;ngulo de Incid&ecirc;ncia Solar';
$strSunAzimuth = 'Azimut del Sol';
$strSunElevation = 'Elevaci&oacute;n del Sol';
$strCart = 'Colocar en el Carro de Compras';
$strPerProd = 'Producto Personalizado';
$strAction = 'Acci&oacute;n';
$strNoScene = '&iexcl;No se encontr&oacute; ninguna escena!';
$strClose = 'Cerrar';
$strAlter = "Alterar Par&aacute;metros"; // se usar a codifica�ao "&acirc;" para o "�", ocorre problema no script ProdForm :
                                  // quando $action = "Alterar Par�metros", $strAlter N�O � igual a $action !!! 
$strImgparms = "Par&aacute;metros de la Imagen"; 
$strActimgparms = "OK! &nbsp; Par&aacute;metros Actualizados de la Imagen"; 
$strInformation = 'Informaci&oacute;n';
$strLocation = 'Localizaci&oacute;n';
?>
