<?php
$strScene = 'Cena';
$strSatelite = 'Sat&eacute;lite';
$strSensor = 'Sensor';
$strBase = '&Oacute;rbita';
$strPonto = 'Ponto';
$strData = 'Data de Passagem';
$strTLLat = 'Latitude Norte';
$strTLLon = 'Longitude Oeste';
$strBRLat = 'Latitude Sul';
$strBRLon = 'Longitude Leste';
$strCenter = 'Tempo Central';
$strStartT = 'Tempo Inicial';
$strStopT = 'Tempo Final';
$strIngest = 'Data de Ingest&atilde;o';
$strImg = 'Orienta&ccedil;&atilde;o da Imagem';
$strPerMissSwaths = 'Varreduras Perdidas (%)';
$strMetodoCobert = 'M&eacute;todo de Cobertura de Nuvem';
$strOrbita = 'Revolu&ccedil;&atilde;o';
$strBitSlips = 'Perda de Bits';
$strMissSwaths = 'Varreduras Perdidas';
$strSyncLosses = 'Perda de Sincronismo';
$strCobertura = 'Cobertura de Nuvens';
$strOffNadirAngle = '&Acirc;ngulo Nadir';
$strSunIncidenceAngle = '&Acirc;ngulo de Incid&ecirc;ncia Solar';
$strSunAzimuth = 'Azimuth Sol';
$strSunElevation = 'Eleva&ccedil;&atilde;o do Sol';
$strCart = 'Colocar no Carrinho';
$strPerProd = 'Produto Personalizado';
$strAction = 'A&ccedil;&atilde;o';
$strNoScene = 'Nenhuma cena encontrada !';
$strClose = 'Fechar';
$strAlter = "Alterar Parametros"; // se usar a codifica�ao "&acirc;" para o "�", ocorre problema no script ProdForm :
                                  // quando $action = "Alterar Par�metros", $strAlter N�O � igual a $action !!! 
$strImgparms = "Par&acirc;metros da Imagem"; 
$strActimgparms = "OK ! &nbsp; Par&acirc;metros Atualizados da Imagem"; 
$strInformation = 'Informa&ccedil;&otilde;es';
$strLocation = 'Localiza&ccedil;&atilde;o';
?>
