<?php
$strScene = 'Sc�ne';
$strSatelite = 'Satellite'; 
$strSensor = 'Capteur';
$strBase = 'Orbite';
$strPonto = 'Point';
$strData = 'Date de Passage';
$strTLLat = 'Latitude Nord';
$strTLLon = 'Longitude Ouest';
$strBRLat = 'Latitude Sud';
$strBRLon = 'Longitude Est';
$strCenter = 'Temps Central'; 
$strStartT = 'Temps Initial'; 
$strStopT = 'Temps Final'; 
$strIngest = "Date d'Absorbtion"; 
$strImg = "Orientation de l'Image"; 
$strPerMissSwaths = 'Rasters Perdus (%)'; 
$strMetodoCobert = 'M�thode de Couverture nuageuse'; 
$strOrbita = 'R�volution';
$strBitSlips = 'Perte de Bits';
$strMissSwaths = 'Rasters Perdus';
$strSyncLosses = 'Perte de Synchronisme';
$strCobertura = 'Couverture Nuageuse'; 
$strOffNadirAngle = 'Angle Nadir';
$strSunIncidenceAngle = 'L Angle de Incidence Solaire';
$strSunAzimuth = 'Azimut Soleil'; 
$strSunElevation = 'El�vation du Soleil'; 
$strCart = 'Mettre dans le panier'; 
$strPerProd = 'Produit Personnalis�'; 
$strAction = 'Action';
$strNoScene = 'Aucune sc�ne trouv�e !'; 
$strClose = 'Fermer'; 
$strAlter = "Modifier les param�tres"; // se usar a codifica�ao "&acirc;" para o "�", ocorre problema no script ProdForm : 
						                          // quando $action = "Alterar Par�metros", $strAlter N�O � igual a $action !!!
$strImgparms = "Param�tres de l'Image";
$strActimgparms = "OK ! &nbsp; Param�tres de l'Image actualis�s";
$strInformation = 'Informations'; 
$strLocation = 'Localisation'; 
?>
