<?php
$strUsr = 'Usuario';
$strMess0 = '<font color=red>Por favor completar los campos:';
$strMess1 = 'Nombre de Usuario ya utilizado. Por favor, escoja otro nombre.<br>';
$strMess2 = '&iexcl;Registro realizado con &eacute;xito!<br>';
$strMess3 = '&iexcl;ya registrado!<br>';
$strMess4 = '&iexcl;Actualizado con &eacute;xito!<br>';
$strMess5 = '<font color=red>E-mail no validado por nuestro sistema! Mensaje:';
$strMess6 = '<font color=red>Problema en el Registro del Usuario';
$strMess7 = '<font color=red>Problema modificando Usuario';
$strRegister = 'Registro';
$strFullname = 'Nombre completo';
$strPass = 'Clave';
$strPhone = 'Tel&eacute;fono';
$strStreet = 'Calle';
$strNumber = 'N&uacute;mero';
$strZip = 'C&oacute;digo Postal';
$strCity = 'Ciudad';
$strState = 'Estado';
$strCountry = 'Pa&iacute;s';
$strOrganization = 'Nombre de la Organizaci&oacute;n';
$strOrgType = 'Tipo de Organizaci&oacute;n';
$strActivity = 'Sector de Actividad';
$strBregister = 'Registrar';
$strBupdate = 'Actualizar';
$strBClear = 'Limpiar';
$strComp = 'Complemento';
$strDistrict = 'Urbanización';
$strOut = 'Cerrar';
$strNoupdate = "&iexcl;Actualizaci&oacute;n s&oacute;lo despu&eacute;s de entrar! ";
$strCommerce = 'Comercializaci&oacute;n de Datos';
$strStateComp = 'Empresa Estatal';
$strPrivtComp = 'Empresa Privada';
$strBasicEduc = 'Educaci&oacute;n B&aacute;sica'; 
$strHigherEduc = 'Educaci&oacute;n Superior'; 
$strGradEduc = 'Post Graduaci&oacute;n'; 
$strLocalGovr = 'Gobierno Municipal'; 
$strStateGovr = 'Gobierno Estatal';
$strFederGovr = 'Gobierno Federal';
$strConsultant = 'Consultor&iacute;a';
$strNGO = 'ONG';
$strOther = 'Otro';

$strAgricult = 'Agricultura';
$strBiology = 'Biolog&iacute;a';
$strCartograf = 'Cartograf&iacute;a';
$strEnvironment = 'Medio Ambiente';
$strEducation = 'Educaci&oacute;n';
$strForestry = '&Aacute;rea Forestal';
$strGeography = 'Geograf&iacute;a';
$strGeology = 'Geolog&iacute;a';
$strHealth = 'Salud';
$strHidrology = 'Hidrolog&iacute;a';
$strImageProc = 'Procesamiento de Im&aacute;genes';
$strPlannig = 'Planeamiento';
$strSocioEcon = 'Socioeconom&iacute;a';
$strTransport = 'Transportes';
?>
