<?php
$strUsr = 'Usu&aacute;rio'; 
$strMess0 = '<font color=red>Favor preencher os campos : ';
$strMess1 = 'Nome de Usu&aacute;rio j&aacute; utilizado. Por favor, escolha outro nome.<br>';
$strMess2 = 'cadastrado com sucesso !<br>';
$strMess3 = 'j&aacute; cadastrado !<br>';
$strMess4 = 'atualizado com sucesso!<br>';
$strMess5 = '<font color=red>E-mail n&atilde;o validado pelo nosso sistema! Mensagem:';
$strMess6 = '<font color=red>Problema no Cadastramento do Usu&aacute;rio';
$strMess7 = '<font color=red>Problema modificando Usu&aacute;rio';
$strRegister = 'Cadastro';
$strFullname = 'Nome completo';
$strPass = 'Senha';
$strPhone = 'Telefone';
$strStreet = 'Logradouro';
$strNumber = 'N&uacute;mero';
$strZip = 'CEP';
$strCity = 'Cidade';
$strState = 'Estado';
$strCountry = 'Pa&iacute;s';
$strOrganization = 'Nome da Organiza&ccedil;&atilde;o';
$strOrgType = 'Tipo de Organiza&ccedil;&atilde;o';
$strActivity = 'Setor de Atividade';
$strBregister = 'Registrar';
$strBupdate = 'Atualizar';
$strBClear = 'Limpar';
$strComp = 'Complemento';
$strDistrict = 'Bairro';
$strOut = 'Fechar';
$strNoupdate = "Atualiza&ccedil;&atilde;o somente ap&oacute;s o Login ! ";

$strCommerce = 'Comercializa&ccedil;&atilde;o de Dados';
$strStateComp = 'Empresa Estatal';
$strPrivtComp = 'Empresa Privada';
$strBasicEduc = 'Educa&ccedil;&atilde;o B&aacute;sica'; 
$strHigherEduc = 'Educa&ccedil;&atilde;o Superior'; 
$strGradEduc = 'P&oacute;s Gradua&ccedil;&atilde;o'; 
$strLocalGovr = 'Governo Municipal'; 
$strStateGovr = 'Governo Estadual';
$strFederGovr = 'Governo Federal';
$strConsultant = 'Consultoria';
$strNGO = 'ONG';
$strOther = 'Outro';

$strAgricult = 'Agricultura';
$strBiology = 'Biologia';
$strCartograf = 'Cartografia';
$strEnvironment = 'Meio Ambiente';
$strEducation = 'Educa&ccedil;&atilde;o';
$strForestry = 'Floresta';
$strGeography = 'Geografia';
$strGeology = 'Geologia';
$strHealth = 'Sa&uacute;de';
$strHidrology = 'Hidrologia';
$strImageProc = 'Processamento de Imagens';
$strPlannig = 'Planejamento';
$strSocioEcon = 'Socioeconomia';
$strTransport = 'Transportes';
?>