<?php 
$strUsr = 'Utilisateur';
$strMess0 = '<font color=red>Veuillez remplir les champs : ';
$strMess1 = "Nom de l'Utilisateur déjà utilisé. Veuillez choisir s'il vous plait un autre nom.<br>";
$strMess2 = 'inscrit avec succès !<br>';
$strMess3 = 'déjà inscrit !<br>';
$strMess4 = 'actualisé avec succès!<br>';
$strMess5 = '<font color=red>E-mail non valide pour notre système! Message:';
$strMess6 = "<font color=red>Problème pour l'inscription de l'Utilisateur";
$strMess7 = '<font color=red>Problème modifiant Utilisateur';
$strRegister = 'Registre';
$strFullname = 'Nom complet';
$strPass = 'Mot de passe';
$strPhone = 'Téléphone';
$strStreet = 'Rue';
$strNumber = 'Numéro';
$strZip = 'CEP';
$strCity = 'Ville';
$strState = 'Etat';
$strCountry = 'Pays';
$strOrganization = "Nom de l'Organisation";
$strOrgType = "Type d'Organisation";
$strActivity = "Secteur d'Activité";
$strBregister = 'Inscrire';
$strBupdate = 'Actualiser';
$strBClear = 'Nettoyer';
$strComp = 'Complément';
$strDistrict = 'Quartier';
$strOut = 'Fermer';
$strNoupdate = "Actualisation seulement après le Login ! ";

$strCommerce = 'Commercialisation de Données';
$strStateComp = 'Entreprise Publique';
$strPrivtComp = 'Entreprise Privée';
$strBasicEduc = 'Education Basique'; 
$strHigherEduc = 'Education supérieure'; 
$strGradEduc = 'PostGraduate'; 
$strLocalGovr = 'Collectivité locale'; 
$strStateGovr = 'Préfecture';
$strFederGovr = 'Gouvernement Fédéral';
$strConsultant = 'Consultation';
$strNGO = 'ONG';
$strOther = 'Autre';

$strAgricult = 'Agriculture';
$strBiology = 'Biologie';
$strCartograf = 'Cartographie';
$strEnvironment = 'Environnement';
$strEducation = 'Education';
$strForestry = 'Botanique';
$strGeography = 'Géographie';
$strGeology = 'Géologie';
$strHealth = 'Santé';
$strHidrology = 'Hydrologie';
$strImageProc = "Traitement d'Images";
$strPlannig = 'Planification';
$strSocioEcon = 'Socio-économie';
$strTransport = 'Transports';
?>